package lefevre

import "unicode/utf8"

// fourcc creates a four-character code from four bytes, matching the KBTS_FOURCC macro.
func fourcc(a, b, c, d byte) uint32 {
	return uint32(a) | uint32(b)<<8 | uint32(c)<<16 | uint32(d)<<24
}

// Direction represents the directionality of text.
type Direction uint8

const (
	DirectionUnknown Direction = iota
	DirectionLTR
	DirectionRTL
)

// Reverse returns the opposite direction. Unknown stays Unknown.
func (d Direction) Reverse() Direction {
	switch d {
	case DirectionLTR:
		return DirectionRTL
	case DirectionRTL:
		return DirectionLTR
	default:
		return DirectionUnknown
	}
}

// String returns "LTR", "RTL", or "Unknown".
func (d Direction) String() string {
	switch d {
	case DirectionLTR:
		return "LTR"
	case DirectionRTL:
		return "RTL"
	default:
		return "Unknown"
	}
}

// BreakFlags is a bitfield indicating what type of break occurred at a position.
type BreakFlags uint8

const (
	BreakFlagDirection          BreakFlags = 1 << iota // Direction change (LTR <-> RTL)
	BreakFlagScript                                    // Script change
	BreakFlagGrapheme                                  // Grapheme cluster boundary
	BreakFlagWord                                      // Word boundary
	BreakFlagLineSoft                                  // Optional line break point
	BreakFlagLineHard                                  // Mandatory line break (newline/paragraph)
	BreakFlagManual                                    // User-requested break
	BreakFlagParagraphDirection                        // Paragraph direction change

	BreakFlagLine = BreakFlagLineSoft | BreakFlagLineHard
	BreakFlagAny  = BreakFlagDirection | BreakFlagScript | BreakFlagGrapheme | BreakFlagWord | BreakFlagLineSoft | BreakFlagLineHard
)

// HasAll returns true if f contains all bits in flag.
func (f BreakFlags) HasAll(flagsQuery BreakFlags) bool { return f&flagsQuery == flagsQuery }

// IsLineBreak returns true if either soft or hard line break flag is set.
func (f BreakFlags) IsLineBreak() bool { return f&BreakFlagLine != 0 }

// IsHardBreak returns true if the hard line break flag is set.
func (f BreakFlags) IsHardBreak() bool { return f&BreakFlagLineHard != 0 }

// GlyphFlags is a bitfield for glyph shaping properties.
type GlyphFlags uint32

const (
	GlyphFlagIsol                 GlyphFlags = 1 << iota // Isolated form (Arabic)
	GlyphFlagFina                                        // Final form (Arabic)
	GlyphFlagFin2                                        // Terminal form #2
	GlyphFlagFin3                                        // Terminal form #3
	GlyphFlagMedi                                        // Medial form (Arabic)
	GlyphFlagMed2                                        // Medial form #2
	GlyphFlagInit                                        // Initial form (Arabic)
	GlyphFlagLJMO                                        // Leading Jamo (Hangul)
	GlyphFlagVJMO                                        // Vowel Jamo (Hangul)
	GlyphFlagTJMO                                        // Trailing Jamo (Hangul)
	GlyphFlagRPHF                                        // Reph form (Indic)
	GlyphFlagBLWF                                        // Below-base form (Indic)
	GlyphFlagHALF                                        // Half form (Indic)
	GlyphFlagPSTF                                        // Post-base form (Indic)
	GlyphFlagABVF                                        // Above-base form (Indic)
	GlyphFlagPREF                                        // Pre-base form (Indic)
	GlyphFlagNUMR                                        // Numerator (fraction)
	GlyphFlagFRAC                                        // Fraction
	GlyphFlagDNOM                                        // Denominator (fraction)
	GlyphFlagCFAR                                        // Conjunct form after Ro
	GlyphFlagDoNotDecompose                              // Glyph should not be decomposed
	GlyphFlagFirstInMultiple                             // First glyph in multiple substitution
	GlyphFlagNoBreak                                     // Do not break at this glyph
	GlyphFlagCursive                                     // Cursive attachment
	GlyphFlagGeneratedByGSUB                             // Generated by GSUB substitution
	GlyphFlagUsedInGPOS                                  // Used in GPOS positioning
	GlyphFlagSTCHEndpoint                                // Stretch endpoint
	GlyphFlagSTCHExtension                               // Stretch extension
	GlyphFlagLigature                                    // Ligature glyph
	GlyphFlagMultipleSubstitution                        // Result of multiple substitution
)

// Has returns true if f contains all bits in flag.
func (f GlyphFlags) Has(flag GlyphFlags) bool { return f&flag == flag }

// Shaper identifies the script-specific shaping engine.
type Shaper uint8

const (
	ShaperDefault Shaper = iota
	ShaperArabic
	ShaperHangul
	ShaperHebrew
	ShaperIndic
	ShaperKhmer
	ShaperMyanmar
	ShaperTibetan
	ShaperUSE
)

// String returns the shaper name.
func (s Shaper) String() string {
	switch s {
	case ShaperDefault:
		return "Default"
	case ShaperArabic:
		return "Arabic"
	case ShaperHangul:
		return "Hangul"
	case ShaperHebrew:
		return "Hebrew"
	case ShaperIndic:
		return "Indic"
	case ShaperKhmer:
		return "Khmer"
	case ShaperMyanmar:
		return "Myanmar"
	case ShaperTibetan:
		return "Tibetan"
	case ShaperUSE:
		return "USE"
	default:
		return "Unknown"
	}
}

// IsComplex returns true if this shaper requires complex shaping support.
func (s Shaper) IsComplex() bool { return s != ShaperDefault }

// joiningFeature represents an Arabic joining form.
type joiningFeature uint8

const (
	joiningFeatureNone joiningFeature = iota
	joiningFeatureIsol
	joiningFeatureFina
	joiningFeatureFin2
	joiningFeatureFin3
	joiningFeatureMedi
	joiningFeatureMed2
	joiningFeatureInit
)

// JapaneseLineBreakStyle controls kinsoku rules for Japanese text.
type JapaneseLineBreakStyle uint8

const (
	JapaneseLineBreakStrict JapaneseLineBreakStyle = iota
	JapaneseLineBreakNormal
	JapaneseLineBreakLoose
)

// userIDMode controls how user IDs are generated for codepoints.
type userIDMode uint8

const (
	userIDCodepointIndex userIDMode = iota
	userIDSourceIndex
)

// ShapeError represents errors during shaping.
type ShapeError uint8

const (
	ShapeErrorNone ShapeError = iota
	ShapeErrorInvalidFont
	ShapeErrorTextBeforeBegin
	ShapeErrorOutOfMemory
)

// Error implements the error interface.
func (e ShapeError) Error() string {
	switch e {
	case ShapeErrorNone:
		return "no error"
	case ShapeErrorInvalidFont:
		return "invalid font"
	case ShapeErrorTextBeforeBegin:
		return "text given before calling Begin"
	case ShapeErrorOutOfMemory:
		return "out of memory"
	default:
		return "unknown shape error"
	}
}

// FontStyleFlags is a bitfield for font style information.
type FontStyleFlags uint8

const (
	FontStyleRegular FontStyleFlags = 0
	FontStyleBold    FontStyleFlags = 1 << iota
	FontStyleItalic
)

// FontWeight represents the weight of a font.
type FontWeight uint8

const (
	FontWeightUnknown FontWeight = iota
	FontWeightThin
	FontWeightExtraLight
	FontWeightLight
	FontWeightNormal
	FontWeightMedium
	FontWeightSemiBold
	FontWeightBold
	FontWeightExtraBold
	FontWeightBlack
)

// FontWidth represents the width/stretch of a font.
type FontWidth uint8

const (
	FontWidthUnknown FontWidth = iota
	FontWidthUltraCondensed
	FontWidthExtraCondensed
	FontWidthCondensed
	FontWidthSemiCondensed
	FontWidthNormal
	FontWidthSemiExpanded
	FontWidthExpanded
	FontWidthExtraExpanded
	FontWidthUltraExpanded
)

// Glyph is the output of text shaping: a positioned glyph ready for rasterization.
type Glyph struct {
	Codepoint rune
	ID        uint16 // Glyph index in font
	UserID    int    // User-assigned or auto-assigned tracking index

	OffsetX, OffsetY   int32 // GPOS positioning offset
	AdvanceX, AdvanceY int32 // Advance to next glyph

	Flags          GlyphFlags
	joiningFeature joiningFeature
	combiningClass uint8
}

// Run is a contiguous sequence of shaped glyphs with uniform properties.
type Run struct {
	Font               *Font
	Script             Script
	Direction          Direction
	ParagraphDirection Direction
	Flags              BreakFlags
	Glyphs             []Glyph
}

// Break describes a segmentation break point in the input text.
type Break struct {
	Position           int
	Flags              BreakFlags
	Direction          Direction
	ParagraphDirection Direction
	Script             Script
}

// FeatureOverride controls a specific OpenType feature's value.
type FeatureOverride struct {
	Tag   FeatureTag
	Value int
}

// FontInfo holds metadata about a loaded font.
type FontInfo struct {
	Family, Subfamily    string
	FullName             string
	PostScriptName       string
	Copyright, Version   string
	Manufacturer         string
	TypographicFamily    string
	TypographicSubfamily string
	StyleFlags           FontStyleFlags
	Weight               FontWeight
	Width                FontWidth
	// Font metrics (from head, hhea, OS/2 tables).
	UnitsPerEm             uint16
	XMin, YMin, XMax, YMax int16
	Ascent, Descent        int16
	LineGap                int16
	CapHeight              int16
}

// Font is a parsed font resource. Create with FontFromMemory.
type Font struct {
	data       []byte                 // retained reference to raw font bytes; must not be modified after parse
	tables     [tableCount]tableEntry // parsed table directory
	cmapFormat uint16                 // selected cmap subtable format (4 or 12)
	cmapOffset uint32                 // absolute offset of selected cmap subtable in data
	err        error                  // sticky parse error
}

// FontFromMemory parses a font from raw TTF/OTF/TTC bytes.
// fontIndex selects which font in a TTC/OTC collection (0-based). For single .ttf/.otf files, use 0.
func FontFromMemory(data []byte, fontIndex int) (*Font, error) {
	return fontFromMemory(data, fontIndex)
}

// FontCount returns the number of fonts in a TTC/OTF/TTF byte slice.
// Returns 0 for invalid or empty data.
func FontCount(data []byte) int {
	return fontCount(data)
}

// IsValid reports whether the font was successfully parsed.
func (f *Font) IsValid() bool {
	return f != nil && f.err == nil && f.data != nil
}

// Info returns metadata about the font.
// Returns zero FontInfo if the font is invalid.
func (f *Font) Info() FontInfo {
	return f.fontInfo()
}

// GlyphID returns the glyph index for a codepoint via the font's cmap table.
// Returns 0 (.notdef) if the codepoint is not mapped or the font is invalid.
func (f *Font) GlyphID(codepoint rune) uint16 {
	return f.glyphID(codepoint)
}

// BreakConfigFlags controls break generation behavior.
type BreakConfigFlags uint8

const (
	BreakConfigNone                        BreakConfigFlags = 0
	BreakConfigEndOfTextGeneratesHardBreak BreakConfigFlags = 1
)

// Breaker is a high-level streaming text segmenter.
// Feed text via AppendBreak, then call End to flush remaining breaks.
// The zero value is ready to use with default settings.
type Breaker struct {
	Direction Direction
	JStyle    JapaneseLineBreakStyle
	Flags     BreakConfigFlags
	state     BreakState
	begun     bool
}

// AppendBreak processes all complete runes in text, appending breaks to dst.
// Returns the extended slice and the number of bytes consumed.
// Incomplete trailing UTF-8 sequences are not consumed.
// Never sets end-of-text; call End after the last chunk.
func (b *Breaker) AppendBreak(dst []Break, text []byte) ([]Break, int) {
	if !b.begun {
		b.state.Begin(b.Direction, b.JStyle, b.Flags)
		b.begun = true
	}
	var bytesConsumed int
	for bytesConsumed < len(text) {
		r, size := utf8.DecodeRune(text[bytesConsumed:])
		if r == utf8.RuneError && size <= 1 {
			break // incomplete or invalid trailing byte
		}
		bytesConsumed += size
		b.state.AddCodepoint(r, 1, false)
		for {
			br, ok := b.state.Next()
			if !ok {
				break
			}
			dst = append(dst, br)
		}
	}
	return dst, bytesConsumed
}

// End signals end-of-text and flushes remaining breaks to dst.
// After End, the Breaker can be reused for new text.
func (b *Breaker) End(dst []Break) []Break {
	b.state.End()
	for {
		br, ok := b.state.Next()
		if !ok {
			break
		}
		dst = append(dst, br)
	}
	b.begun = false
	return dst
}

// BreakState is a streaming text segmentation state machine.
// Zero value is valid; call Begin before feeding codepoints.
type BreakState struct {
	s breakStateInternal
}

// GuessTextProperties scans text for the first strong directional character
// and first identifiable script. Useful for mono-script, mono-direction text.
func GuessTextProperties(text string) (Direction, Script) {
	script := ScriptUnknown
	dir := DirectionUnknown

	if len(text) == 0 {
		return DirectionLTR, ScriptUnknown
	}

	var bs BreakState
	bs.Begin(DirectionUnknown, JapaneseLineBreakNormal, BreakConfigNone)
	for i, r := range text {
		// Check if this is the last rune by seeing if the next byte position is at or past the end.
		eot := i+utf8.RuneLen(r) >= len(text)
		bs.AddCodepoint(r, 1, eot)
		for {
			b, ok := bs.Next()
			if !ok {
				break
			}
			if script == ScriptUnknown && b.Flags.HasAll(BreakFlagScript) {
				script = b.Script
			}
			if dir == DirectionUnknown && b.Flags.HasAll(BreakFlagDirection) {
				dir = b.Direction
			}
		}
		if script != ScriptUnknown && dir != DirectionUnknown {
			break
		}
	}

	if dir == DirectionUnknown {
		dir = DirectionLTR
	}
	return dir, script
}
