// Command gentables extracts Unicode property tables from kb_text_shape.h
// and generates Go source files.
package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"regexp"
	"strings"
)

type tableSpec struct {
	cName   string
	goName  string
	goType  string
	comment string
}

var tables = []tableSpec{
	// Segmentation tables
	{"kbts__UnicodeGraphemeBreakClass_PageIndices", "graphemeBreakClassPageIndices", "uint8", "grapheme break class page indices"},
	{"kbts__UnicodeGraphemeBreakClass_Data", "graphemeBreakClassData", "uint8", "grapheme break class data"},
	{"kbts__UnicodeLineBreakClass_PageIndices", "lineBreakClassPageIndices", "uint8", "line break class page indices"},
	{"kbts__UnicodeLineBreakClass_Data", "lineBreakClassData", "uint8", "line break class data"},
	{"kbts__UnicodeWordBreakClass_PageIndices", "wordBreakClassPageIndices", "uint8", "word break class page indices"},
	{"kbts__UnicodeWordBreakClass_Data", "wordBreakClassData", "uint8", "word break class data"},
	{"kbts__UnicodeBidirectionalClass_PageIndices", "bidiClassPageIndices", "uint8", "bidirectional class page indices"},
	{"kbts__UnicodeBidirectionalClass_Data", "bidiClassData", "uint8", "bidirectional class data"},
	{"kbts__UnicodeScriptExtension_PageIndices", "scriptExtensionPageIndices", "uint8", "script extension page indices"},
	{"kbts__UnicodeScriptExtension_Data", "scriptExtensionData", "uint16", "script extension data"},
	{"kbts__UnicodeFlags_PageIndices", "unicodeFlagsPageIndices", "uint8", "unicode flags page indices"},
	{"kbts__UnicodeFlags_Data", "unicodeFlagsData", "uint8", "unicode flags data"},
	{"kbts__UnicodeMirrorCodepoint_PageIndices", "mirrorCodepointPageIndices", "uint8", "mirror codepoint page indices"},
	{"kbts__UnicodeMirrorCodepoint_Data", "mirrorCodepointData", "uint32", "mirror codepoint data"},
}

// Also extract: kbts__ScriptExtensions array and kbts_GraphemeBreakTransition table.

func main() {
	if len(os.Args) < 3 {
		log.Fatal("usage: gentables <input.h> <output.go>")
	}
	inputPath := os.Args[1]
	outputPath := os.Args[2]

	data, err := os.ReadFile(inputPath)
	if err != nil {
		log.Fatal(err)
	}
	content := string(data)

	out, err := os.Create(outputPath)
	if err != nil {
		log.Fatal(err)
	}
	defer out.Close()

	w := bufio.NewWriter(out)
	defer w.Flush()

	fmt.Fprintln(w, "// Code generated by cmd/gentables; DO NOT EDIT.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "package lefevre")
	fmt.Fprintln(w)

	for _, t := range tables {
		values := extractArray(content, t.cName)
		if values == "" {
			log.Printf("WARNING: table %s not found", t.cName)
			continue
		}
		fmt.Fprintf(w, "// %s\n", t.comment)
		fmt.Fprintf(w, "var %s = [...]%s{%s}\n\n", t.goName, t.goType, values)
	}

	// Extract ScriptExtensions array
	scriptExt := extractArray(content, "kbts__ScriptExtensions")
	if scriptExt != "" {
		fmt.Fprintln(w, "// script extensions array")
		fmt.Fprintf(w, "var scriptExtensions = [...]uint8{%s}\n\n", scriptExt)
	}

	// Extract GraphemeBreakTransition table
	gbt := extractNestedArray(content, "kbts_GraphemeBreakTransition")
	if gbt != "" {
		fmt.Fprintln(w, "// grapheme break transition table [class][state]")
		fmt.Fprintf(w, "var graphemeBreakTransition = %s\n\n", gbt)
	}

	fmt.Println("Generated", outputPath)
}

var arrayDeclRe = regexp.MustCompile(`(?:static\s+)?(?:kbts_(?:u8|u16|u32|s32)\s+)(\w+)\[`)

func extractArray(content, name string) string {
	// Find "name[...] = {"
	idx := strings.Index(content, name+"[")
	if idx < 0 {
		idx = strings.Index(content, name+" [")
		if idx < 0 {
			return ""
		}
	}
	// Find opening brace
	braceStart := strings.Index(content[idx:], "{")
	if braceStart < 0 {
		return ""
	}
	braceStart += idx

	// Find matching closing brace
	depth := 0
	end := braceStart
	for i := braceStart; i < len(content); i++ {
		if content[i] == '{' {
			depth++
		} else if content[i] == '}' {
			depth--
			if depth == 0 {
				end = i
				break
			}
		}
	}

	inner := content[braceStart+1 : end]
	// Clean up: remove C-style comments, normalize whitespace
	inner = removeCComments(inner)
	inner = strings.TrimSpace(inner)
	// Remove trailing comma if present before closing brace
	inner = strings.TrimRight(inner, ", \t\n\r")
	return inner
}

func extractNestedArray(content, name string) string {
	idx := strings.Index(content, name+"[")
	if idx < 0 {
		idx = strings.Index(content, name+" [")
		if idx < 0 {
			return ""
		}
	}
	braceStart := strings.Index(content[idx:], "{")
	if braceStart < 0 {
		return ""
	}
	braceStart += idx

	depth := 0
	end := braceStart
	for i := braceStart; i < len(content); i++ {
		if content[i] == '{' {
			depth++
		} else if content[i] == '}' {
			depth--
			if depth == 0 {
				end = i
				break
			}
		}
	}

	inner := content[braceStart+1 : end]
	inner = removeCComments(inner)

	// Parse rows: each { ... } is a row
	var rows []string
	for {
		rowStart := strings.Index(inner, "{")
		if rowStart < 0 {
			break
		}
		rowEnd := strings.Index(inner[rowStart:], "}")
		if rowEnd < 0 {
			break
		}
		rowEnd += rowStart
		row := strings.TrimSpace(inner[rowStart+1 : rowEnd])
		row = strings.TrimRight(row, ", ")
		rows = append(rows, row)
		inner = inner[rowEnd+1:]
	}

	if len(rows) == 0 {
		return ""
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("[%d][%d]uint8{\n", len(rows), countFields(rows[0])))
	for _, row := range rows {
		sb.WriteString("\t{")
		sb.WriteString(row)
		sb.WriteString("},\n")
	}
	sb.WriteString("}")
	return sb.String()
}

func countFields(row string) int {
	parts := strings.Split(row, ",")
	count := 0
	for _, p := range parts {
		if strings.TrimSpace(p) != "" {
			count++
		}
	}
	return count
}

func removeCComments(s string) string {
	// Remove /* ... */ comments
	for {
		start := strings.Index(s, "/*")
		if start < 0 {
			break
		}
		end := strings.Index(s[start:], "*/")
		if end < 0 {
			break
		}
		s = s[:start] + s[start+end+2:]
	}
	// Remove // ... comments
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if idx := strings.Index(line, "//"); idx >= 0 {
			lines[i] = line[:idx]
		}
	}
	return strings.Join(lines, "\n")
}
